### ISSUE TITLE
Discourse signup with Facebook doesn't work

### ISSUE THREAD

**Issue by shickey** [ml-learning/lcl#25]
Eric S tried to sign up for discourse using his facebook credentials and ran into an issue. See screenshot attached
![pasted image at 2017_10_16 12_10 pm](https://user-images.githubusercontent.com/1489558/31624380-8afe4250-b270-11e7-8da0-bd5fc3bf9d02.png)

**Comment by morantsur** [comment]
We should set it up with a Facebook developer account.

The instructions are here: https://meta.discourse.org/t/configuring-facebook-login-for-discourse/13394

**Comment by morantsur** [comment]
I'm pretty sure I fixed it, but can't test with my Facebook because it's now the developer connected. Will test tomorrow

**Comment by shickey** [comment]
Jaleesa reported that someone on the FB page contacted her with the same issue this morning. I'll see if I can get more info from her, but will reopen this for now to keep it on our radar
