### ISSUE TITLE
Should the peg in module dropdown indicate current week? Or current page?

### ISSUE THREAD

**Issue by shickey** [ml-learning/lcl#37]
Imagine it's week 5 (Play) and I navigate back to week 2 (Projects). Should the blue peg in the modules dropdown in the navbar appear next to week 5 (since it's the current week) or week 2 (since that's the week I'm currently viewing)? I suppose we're already indicating the week we're currently viewing with the title of the dropdown in the navbar, so maybe it's okay that it indicates the current week?

**Comment by morantsur** [comment]
I would lean towards keeping in with the current week, not current page.

**Comment by shickey** [comment]
👍 Sounds good to me.
